services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${GRADING_JOURNAL_DATABASE_USER}
      POSTGRES_PASSWORD: ${GRADING_JOURNAL_DATABASE_PASSWORD}
      POSTGRES_DB: ${GRADING_JOURNAL_DATABASE_NAME}
    ports:
      - "15432:5432"
  api:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8882:8882"
