services:
  grading-journal-postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${GRADING_JOURNAL_DATABASE_USER}
      POSTGRES_PASSWORD: ${GRADING_JOURNAL_DATABASE_PASSWORD}
      POSTGRES_DB: ${GRADING_JOURNAL_DATABASE_NAME}
    ports:
      - "${GRADING_JOURNAL_DATABASE_PORT}:5432"